server:
  port: 8006
spring:
  application:
    name: dubbo
  dubbo:
    server: true
    application:
      name: provider
    registry:
#      address: multicast://224.5.6.7:1234
      #zookeeper 集群
      address: zookeeper://192.168.88.132:2181?backup=192.168.88.132:2182,192.168.88.132:2183
    protocol:
      name: dubbo
      port: 20880
    scan: com.example.demoprovider.service